/*CREATE DATABASE Yeticave_pro
  DEFAULT CHARACTER SET UTF8
  DEFAULT COLLATE utf8_general_ci;*/

USE Yeticave_pro;

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
regist_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email CHAR(120) NOT NULL UNIQUE,
password CHAR(30) NOT NULL UNIQUE,
contact_phone CHAR(12) NOT NULL UNIQUE,
avatar_url VARCHAR(200),
user_name CHAR(120) NOT NULL 
);

CREATE TABLE lots (
id_lot INT AUTO_INCREMENT PRIMARY KEY,
creation_date TIMESTAMP DEFAULT TIMESTAMP,
name CHAR(120) NOT NULL ,
description VARCHAR(700) NOT NULL ,
img_url VARCHAR(200) NOT NULL ,
cat_id INT(11) NOT NULL,
start_price INT(11) NOT NULL,
end_time DATETIME,
rate_step INT(11)NOT NULL,
user_id INT(11) NOT NULL,
act_price INT(11) DEFAULT NULL


);

CREATE TABLE cats (
id INT AUTO_INCREMENT PRIMARY KEY,
category CHAR(120) NOT NULL UNIQUE
);

CREATE TABLE rates (
id INT AUTO_INCREMENT PRIMARY KEY,
rate_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
user_id INT(11) NOT NULL, 
lot_id INT(11) NOT NULL,
rsumm INT(11) NOT NULL
);